{% set name = "sphinx-autoapi" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e4b3ecf8fbcc6e8300491248440ad4d4bbfa6d0668f0bd44365d22aaf4db46d

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - astroid
    - pyyaml
    - wheel ==0.24.0
    - sphinx
    - sphinxcontrib-golangdomain
    - sphinxcontrib-dotnetdomain
    - unidecode

test:
  requires:
    - pydocstyle
    - salvus_mesher_lite  # [osx]
  imports:
    - autoapi

about:
  home: http://github.com/rtfd/sphinx-autoapi
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.mit'
  summary: Sphinx auto API documentation generator
  doc_url: http://sphinx-autoapi.readthedocs.io/en/latest/
  dev_url: https://github.com/rtfd/sphinx-autoapi

extra:
  recipe-maintainers:
    - CurtLH
