{% set name = "sphinx-autoapi" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f76ef71d443c6a9ad5e1b326d4dfc196e2080e8b46141c45d1bb47a73a34f190

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - astroid
    - pyyaml
    - sphinx
    - sphinxcontrib-golangdomain
    - sphinxcontrib-dotnetdomain
    - unidecode

test:
  requires:
    - pydocstyle
    - salvus_mesher_lite  # [osx]
  imports:
    - autoapi

about:
  home: http://github.com/rtfd/sphinx-autoapi
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.mit
  summary: Sphinx auto API documentation generator
  doc_url: http://sphinx-autoapi.readthedocs.io/en/latest/
  dev_url: https://github.com/rtfd/sphinx-autoapi

extra:
  recipe-maintainers:
    - CurtLH
