travis:
  secure:
    BINSTAR_TOKEN: RBP662zEW3K1x7KmAVyVU5zv80h1fmhaJdwepaSmyNlMi0/k7f0X1gz+EvyP5j5BxlbrUhrT6rx/E+1jI11CXHKHfB/tcL5/hDQZL8P0hm6CESly9IhBuSglb4bHFQv2KN5VE50tt267s7v/z6LZviPzUM18plUCD4JT42oW08hz7c+PfR/X0sgnwomN/3PD+yT3M6QrASBtma0JS7VUBohtU0ybVafg5uF7HJpWgjWVPetizmWweqGX5UHmkiuffqQL0lciVZ98/G27xW8EmohcIAUGwZizWfgrksoIM+iP+WNxYrwYGXu//elyZZdiBpBAb/DLdpwoVfEb05hL1ousVQtqsEZlNvNSd6HuMzDc7CMD9v/YiykK3c43e30iffU3b21vAIA8DPI+sE/KuPaF/rdRRW70q4LgZFdvHTm/Q5orPeFu8djBcvgTuh2VRLqZ2YI2lKp3bvE4NzS/UW1Dsv+M9p+hwXXTw0Lopp2akzgM53GzWJC2vhSBzMm6qpEvUkjqmdDlpNmcygjwRFy/H9q0LcUGBUtyC6DG0ss/7DwrP86AAH6xHhQntRFZp8JEf7XhdSoEjkpiPgTjQrDaLSob9uR4NbMSG7S7oyh+qmUppeKnO90J+TcsxjqDumERCqwf8POBSeWBzsW7bJBWNvqLGCmUrTH/kK6jadA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
