travis:
  secure:
    BINSTAR_TOKEN: WcVDM85DmrjhJIZdam1/gLO6AnXPVeYvwB3N9BaVTvOyu07oVME/QwUErJTDjHfGHmSo+vKx/iCMj6/c0WcJ2CCOu7wpGqUJ6cluivgTCm/jLtXS/l6+UXuxPtg6ylc2E/El/pZ1ZS2W0wk7IDaTVt2N/r9bDv0LkUccz4WOJLNyUyNFOS/iqszGa1c6mo4y+wbivKmRBn/7aSad5fNRuMvuzNE24QSHR8QQaWdjlcMfOBvbjNyO+zV+P6cHTCzwNjAgfwN2Qog1yE4/OILEjcbY9AtnMsZ/ktQKnuiR8ZK7yrtpzHEmBcUjtDJOYH6SaJnFSWT45Tdu9kUfENMXz5APFD3pz4EprFN22t0zbm1QrM/8F7tg9g700I1QwIGEb615b4XzAjFX393G8jVWTTAJhiM8afoiXv2cCHDS2FlqnEPBqT1lr2fUXaga58Qu065IH/q928mABWtIzagPTmWSvfwxAP1pvvSw+FqgkDtBGfYzSsbpgLEMCGUFGFlL760GfPBkONhPTkJbyUybZOvifMEes2aJvxQXe6ZSZs3l11OKM6NiqZCrNoEigPiis8jWrBM/OGLBb+etlBaKKzH+wLKREnDcFqVVlNfiZh8Ei4eWqcfYU7KLzLmhiJ3axBrQVhZc6VKN2DlvBokWNF6Ta3vm4ALXNJ+2SSDW0KI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
